/**
 * ============================================================================
 * src/providers/oracle/checks.ts — "ADD ORACLE CLOUD" FORM + LIVE CHECKS
 * ============================================================================
 *
 * Oracle's API login is an "API key": an RSA key pair you create in the
 * Oracle console. Oracle keeps the PUBLIC half; you download the PRIVATE
 * half (.pem) and give it to us, together with a few ids Oracle shows you
 * in a "Configuration file preview" right after adding the key:
 *
 *     [DEFAULT]
 *     user=ocid1.user.oc1..aaaa...
 *     fingerprint=12:34:56:...
 *     tenancy=ocid1.tenancy.oc1..aaaa...
 *     region=ap-singapore-1
 *     key_file=<path to your private keyfile>
 *
 * When someone submits the form, runChecks() goes through this list and
 * reports each result with a tip:
 *
 *   1. format       — do the OCIDs, fingerprint and region look right?
 *   2. key          — can the private key be read (with the passphrase)?
 *   3. fingerprint  — does the fingerprint belong to THIS key? (computed locally)
 *   4. signin       — does Oracle accept the key? (reads your user)
 *   5. region       — is the tenancy subscribed to the region?
 *   6. permissions  — can the user list machines, networks and disk backups?
 *   7. gpu          — does Oracle offer our GPU shapes to you in that region?
 *
 * 1, 2, 4 are FAILS (nothing is saved). 3 is a warning that explains the
 * sign-in failure that usually follows. 5–7 are WARNINGS: the key is fine and
 * is saved, but launching won't work until they're fixed — typical while a
 * GPU service-limit request is waiting for approval.
 *
 * runChecks never throws for user mistakes: every problem becomes a check
 * with a tip.
 * ============================================================================
 */

import crypto from 'crypto';
import { OracleProvider, fingerprintOfPrivateKey, cleanPrivateKey } from '../OracleProvider';
import { toFriendlyError } from '../errors';
import { oracleConsole, oraclePolicyStatements } from './errors';
import { CredentialCheck, ProviderSetupModule, outcome } from '../shared/types';
import { DEFAULT_REGION, ORACLE_SHAPES, findRegion } from './catalog';

export const ORACLE_SETUP: ProviderSetupModule = {
  intro:
    'Create an API key for your Oracle Cloud user and paste its details here. Machines are created in YOUR tenancy and billed to you by Oracle. ' +
    'In the Oracle console: Profile (top right) → My profile → API keys → Add API key → "Generate API key pair" → Download private key → Add. ' +
    'Oracle then shows a "Configuration file preview" with the tenancy, user, fingerprint and region values below.',
  fields: [
    {
      key: 'tenancyOcid',
      label: 'Tenancy OCID',
      type: 'text',
      required: true,
      placeholder: 'ocid1.tenancy.oc1..aaaaaaaa…',
      help: 'The "tenancy=" line of the Configuration file preview (also: Profile → Tenancy → OCID "Copy").',
    },
    {
      key: 'userOcid',
      label: 'User OCID',
      type: 'text',
      required: true,
      placeholder: 'ocid1.user.oc1..aaaaaaaa…',
      help: 'The "user=" line of the Configuration file preview (also: Profile → My profile → OCID "Copy").',
    },
    {
      key: 'fingerprint',
      label: 'API key fingerprint',
      type: 'text',
      required: true,
      placeholder: '12:34:56:78:9a:bc:de:f0:12:34:56:78:9a:bc:de:f0',
      help: 'The "fingerprint=" line, also listed next to the key under My profile → API keys.',
    },
    {
      key: 'privateKey',
      label: 'API private key (.pem)',
      type: 'file-text',
      required: true,
      accept: '.pem',
      placeholder: '-----BEGIN PRIVATE KEY-----\n…\n-----END PRIVATE KEY-----',
      help: 'The PRIVATE key file you downloaded when adding the API key — not the "_public.pem" one. Upload or paste the whole file.',
      secret: true,
    },
    {
      key: 'passphrase',
      label: 'Private key passphrase',
      type: 'password',
      required: false,
      help: 'Only if you protected the key with a passphrase yourself. Keys generated by the Oracle console have none — leave empty.',
      secret: true,
    },
    {
      key: 'region',
      label: 'Region',
      type: 'text',
      required: true,
      placeholder: DEFAULT_REGION,
      help: 'The "region=" line (your home region), e.g. ap-singapore-1. Machines can still be launched in any region you subscribe to.',
    },
    {
      key: 'compartmentOcid',
      label: 'Compartment OCID',
      type: 'text',
      required: false,
      placeholder: 'ocid1.compartment.oc1..aaaaaaaa… (optional)',
      help: 'Optional. Where machines are created. Empty = the root compartment of your tenancy. Identity & Security → Compartments → copy OCID.',
    },
  ],

  async runChecks(input, opts) {
    const checks: CredentialCheck[] = [];

    // ---- 1. Format ----------------------------------------------------------
    let creds;
    try {
      creds = OracleProvider.parseCredentials(input);
      checks.push({
        id: 'format', label: 'Format', status: 'pass',
        message: `Tenancy, user, fingerprint and region (${creds.region}) look right.`,
      });
    } catch (error) {
      const f = toFriendlyError(error, 'oracle');
      checks.push({ id: 'format', label: 'Format', status: 'fail', message: f.title, tip: [f.explanation, ...f.fixes].join(' ') });
      return outcome(checks, undefined, {});
    }

    const metadata: Record<string, unknown> = {
      tenancyOcid: creds.tenancyOcid,
      userOcid: creds.userOcid,
      fingerprint: creds.fingerprint, // not secret: it's a hash of the PUBLIC key
      region: creds.region,
      compartmentOcid: creds.compartmentOcid,
    };

    // ---- 2. Private key readable (with the passphrase) -------------------------
    try {
      const key = crypto.createPrivateKey({ key: creds.privateKey, format: 'pem', passphrase: creds.passphrase });
      if (key.asymmetricKeyType !== 'rsa') {
        checks.push({
          id: 'key', label: 'Private key', status: 'fail',
          message: `This is a ${key.asymmetricKeyType?.toUpperCase()} key — Oracle API keys must be RSA.`,
          tip: 'Use "Generate API key pair" in the Oracle console, or create one with: openssl genrsa -out oci_api_key.pem 2048',
        });
        return outcome(checks, undefined, metadata);
      }
      checks.push({ id: 'key', label: 'Private key', status: 'pass', message: 'The private key is readable.' });
    } catch (error) {
      const msg = String((error as Error)?.message || '');
      const encrypted = /ENCRYPTED/.test(creds.privateKey);
      checks.push({
        id: 'key', label: 'Private key', status: 'fail',
        message: encrypted && !creds.passphrase
          ? 'This private key is protected by a passphrase, but none was entered.'
          : /bad decrypt|passphrase/i.test(msg)
            ? 'The passphrase doesn\'t unlock this private key.'
            : 'The private key is damaged or incomplete.',
        tip: encrypted
          ? 'Enter the passphrase you chose when creating the key (it\'s case-sensitive).'
          : 'Upload the original .pem file instead of pasting, so nothing is lost. It must include the "-----BEGIN …-----" and "-----END …-----" lines.',
      });
      return outcome(checks, undefined, metadata);
    }

    // ---- 3. Fingerprint matches the key (computed locally) --------------------------
    let keyFingerprint = '';
    try {
      keyFingerprint = fingerprintOfPrivateKey(creds.privateKey, creds.passphrase);
    } catch { /* already reported above */ }
    const fingerprintMismatch = !!keyFingerprint && keyFingerprint !== creds.fingerprint;
    checks.push(fingerprintMismatch
      ? {
          id: 'fingerprint', label: 'Fingerprint', status: 'warn',
          message: `The fingerprint you entered isn't this key's. This key's fingerprint is ${keyFingerprint}.`,
          tip: 'You probably have the fingerprint of a different API key. In My profile → API keys, find the key with the fingerprint shown here — if it\'s not listed, this private key was never added to Oracle: add its public key, or generate a new key pair.',
          consoleUrl: oracleConsole('identity/domains/my-profile/api-keys'),
          consoleLabel: 'Open API keys',
        }
      : { id: 'fingerprint', label: 'Fingerprint', status: 'pass', message: 'The fingerprint matches the private key.' });

    // What gets encrypted and stored (only cleaned-up values).
    const secret = {
      tenancyOcid: creds.tenancyOcid,
      userOcid: creds.userOcid,
      fingerprint: creds.fingerprint,
      privateKey: cleanPrivateKey(creds.privateKey),
      ...(creds.passphrase ? { passphrase: creds.passphrase } : {}),
      region: creds.region,
      compartmentOcid: creds.compartmentOcid,
    };

    // ---- 4. Sign in (read our own user) --------------------------------------------
    const provider = new OracleProvider(secret);
    try {
      const user = await provider.getUser();
      metadata.userName = user.name;
      checks.push({ id: 'signin', label: 'Sign in to Oracle Cloud', status: 'pass', message: `Oracle accepted the key for user "${user.name}".` });
    } catch (error) {
      const f = toFriendlyError(error, 'oracle');
      checks.push({
        id: 'signin', label: 'Sign in to Oracle Cloud', status: 'fail', message: f.title,
        tip: (fingerprintMismatch ? 'Most likely cause: the fingerprint doesn\'t match the key (see above). ' : '') + f.fixes.join(' '),
        consoleUrl: f.consoleUrl, consoleLabel: f.consoleLabel,
      });
      return outcome(checks, undefined, metadata);
    }

    // The region to check GPUs in: the one the launch form asked about, else the saved one.
    const gpuRegion = findRegion(opts.region || '')?.id || creds.region;

    // ---- 5. Region subscribed ----------------------------------------------------------
    try {
      const regions = await provider.listSubscribedRegions();
      const ready = regions.filter((r) => r.status === 'READY').map((r) => r.name);
      metadata.subscribedRegions = ready;
      metadata.homeRegion = regions.find((r) => r.home)?.name;
      const missing = Array.from(new Set([creds.region, gpuRegion])).filter((r) => !ready.includes(r));
      checks.push(missing.length === 0
        ? { id: 'region', label: 'Region', status: 'pass', message: `Your tenancy is subscribed to ${Array.from(new Set([creds.region, gpuRegion])).join(' and ')}.` }
        : {
            id: 'region', label: 'Region', status: 'warn',
            message: `Your tenancy isn't subscribed to ${missing.join(', ')} (subscribed: ${ready.join(', ') || 'none'}).`,
            tip: 'Region menu (top bar of the Oracle console) → Manage regions → Subscribe. Or enter one of your subscribed regions.',
            consoleUrl: oracleConsole('regions/infrastructure'), consoleLabel: 'Manage regions',
          });
    } catch (error) {
      checks.push({ id: 'region', label: 'Region', status: 'warn', message: 'Couldn\'t list your subscribed regions.', tip: toFriendlyError(error, 'oracle').title });
    }

    // ---- 6. Permissions (read-only probes) -------------------------------------------
    let compartmentName = 'tenancy';
    try {
      compartmentName = await provider.getCompartmentName();
      metadata.compartmentName = compartmentName;
    } catch (error) {
      checks.push({
        id: 'compartment', label: 'Compartment', status: 'fail',
        message: 'Oracle can\'t find that compartment (or the user may not see it).',
        tip: 'Check the Compartment OCID (Identity & Security → Compartments), or leave it empty to use the root compartment. ' + toFriendlyError(error, 'oracle').title,
        consoleUrl: oracleConsole('identity/compartments'), consoleLabel: 'Open Compartments',
      });
      return outcome(checks, undefined, metadata);
    }
    const scope = compartmentName === 'tenancy' ? 'tenancy' : `compartment ${compartmentName}`;
    const probes: Array<{ what: string; run: () => Promise<void> }> = [
      { what: 'machines (instance-family)', run: () => provider.probeInstances(creds.region) },
      { what: 'networks (virtual-network-family)', run: () => provider.probeNetworks(creds.region) },
      { what: 'disks and backups (volume-family)', run: () => provider.probeVolumes(creds.region) },
    ];
    const denied: string[] = [];
    let otherError: string | undefined;
    for (const probe of probes) {
      try {
        await probe.run();
      } catch (error) {
        const f = toFriendlyError(error, 'oracle');
        if (f.code === 'OCI_NOT_AUTHORIZED_OR_NOT_FOUND') denied.push(probe.what);
        else otherError = otherError || f.title;
      }
    }
    if (denied.length) {
      checks.push({
        id: 'permissions', label: 'Permissions', status: 'fail',
        message: `The user can't access ${denied.join(', ')} in the ${scope === 'tenancy' ? 'root compartment' : scope}.`,
        tip: 'Put the API user in a group (e.g. "CloudGaming") and, in the ROOT compartment, create a policy (Identity & Security → Policies → Create policy → "Show manual editor") with: ' +
          oraclePolicyStatements('CloudGaming', scope).join(' · ') +
          '. Administrators already have everything; a new policy takes a minute to apply.',
        consoleUrl: oracleConsole('identity/domains/policies'), consoleLabel: 'Open Policies',
      });
      return outcome(checks, undefined, metadata);
    }
    checks.push(otherError
      ? { id: 'permissions', label: 'Permissions', status: 'warn', message: 'Couldn\'t fully check permissions.', tip: otherError }
      : {
          id: 'permissions', label: 'Permissions', status: 'pass',
          message: `The user can see machines, networks and disk backups in the ${scope === 'tenancy' ? 'root compartment' : scope}.`,
          tip: 'These checks only READ. Creating things also needs "manage" rights: ' + oraclePolicyStatements('<your group>', scope).slice(0, 3).join(' · '),
        });

    // ---- 7. GPU shapes offered (service limits) ------------------------------------------
    // Oracle's Limits API (oci-limits) isn't installed, so we can't read the GPU
    // limit number itself. listShapes still tells us whether the GPU shapes are
    // offered to this tenancy in each availability domain.
    const limitsTip =
      'New Oracle accounts have a GPU limit of 0. Open Governance → Limits, Quotas and Usage, choose Service "Compute", your region, ' +
      'search "GPU.A10", and click "Request a service limit increase" for 1 (per availability domain). Free-trial accounts must upgrade to Pay As You Go first. Approval: hours to a couple of days.';
    try {
      const perAd = await provider.listGpuShapes(gpuRegion);
      const offered = perAd.filter((a) => a.shapes.length);
      metadata.gpuShapes = perAd;
      checks.push(offered.length
        ? {
            id: 'gpu', label: `GPU machines in ${gpuRegion}`, status: 'pass',
            message: `Oracle offers you ${offered.map((a) => `${a.shapes.join(', ')} in ${a.ad.split(':').pop()}`).join('; ')}.`,
            tip: 'If a launch still says "LimitExceeded", your GPU service limit is 0 — ' + limitsTip,
            consoleUrl: oracleConsole('limits'), consoleLabel: 'Open Limits',
          }
        : {
            id: 'gpu', label: `GPU machines in ${gpuRegion}`, status: 'warn',
            message: `Oracle doesn't list any of our GPU shapes (${ORACLE_SHAPES.map((s) => s.id).join(', ')}) for you in ${gpuRegion} yet.`,
            tip: limitsTip + ' Or try another region.',
            consoleUrl: oracleConsole('limits'), consoleLabel: 'Request GPU limit',
          });
    } catch (error) {
      checks.push({
        id: 'gpu', label: `GPU machines in ${gpuRegion}`, status: 'warn',
        message: 'Couldn\'t check GPU availability.',
        tip: `${toFriendlyError(error, 'oracle').title}. ${limitsTip}`,
        consoleUrl: oracleConsole('limits'), consoleLabel: 'Open Limits',
      });
    }

    return outcome(checks, secret, metadata);
  },
};
